---
- name: Disable password complexity lmao
  win_security_policy:
     section: System Access
     key: PasswordComplexity
     value: 0

- name: Add domain users
  win_domain_user:
    name: "{{ item }}"
    password: "{{ default_password }}"
    state: present
    update_password: on_create
    upn: "{{ item }}@{{ domain_name }}"
  loop:
    - Maximus
    - Pompey
    - Cicero
    - Plato
    - Socrates
    - Aristotle
    - Epicurus
    - Plutarch
    - Jeffery
    - Jeff
    - Jeofery
    - Matt
    - Martha

- name: Add domain admins
  win_domain_user:
    name: "{{ item }}"
    password: "{{ default_password }}"
    state: present
    groups:
      - Domain Admins
    update_password: on_create
    upn: "{{ item }}@{{ domain_name }}"
  loop:
    - Agustus
    - Cato
    - Sulla
    - Lucius
    - Favonius
    - Julius
    - Marcus
    - Vinicius
    - Octavius