---
# # Deploy router
# - hosts: washington
#   roles:
#     - washington-deployment
#   connection: local
#   gather_facts: False

# Deploy domain controllers
- hosts: alexander
  roles:
    - alexander-deployment

# Deploy file servers
- hosts: julius
  roles:
    - julius-deployment

# Deploy public web server
- hosts: bonaparte
  roles:
    - bonaparte-deployment

# Deploy mail server
- hosts: xerxes
  roles:
    - xerxes-deployment

# Apply Windows standards
- hosts: windows
  roles:
    - windows-standards

# Install docker host
- hosts: churchill
  become: yes
  roles:
    - churchill-deployment
    - gitlab-ci-runner

# Install Graylog
- hosts: leonidas
  become: yes
  roles:
    - leonidas-deployment

# Install LAMP app
- hosts: attila 
  become: yes
  roles:
    - attila-deployment

# Install OpenVPN server
- hosts: ashoka
  become: yes
  roles:
    - ashoka-deployment

# Install public DNS server
- hosts: gandhi
  become: yes
  roles:
    - bsd-standards
    - gandhi-deployment

# Install GitLab
- hosts: ataturk
  become: yes
  roles:
    - ataturk-deployment

# Apply Linux standards
- hosts: linux
  become: yes
  roles:
    - linux-standards

# Apply Linux standards to BSD
- hosts: bsd
  become: yes
  roles:
    - linux-standards

# Install OSSEC clients (linux)
- hosts: linux
  become: yes
  roles:
    - OssecAgents

# Install OSSEC clients (windows)
- hosts: windows
  roles:
    - OssecAgents
