---
# # Deploy router
# - hosts: washington
#   roles:
#     - washington-deployment
#   connection: local
#   gather_facts: False

# Deploy domain controllers

# Apply Linux standards
# Install OSSEC clients (linux)
- hosts: attila
  become: yes
  roles:
    - OssecAgents
