---
- name: Apply the resolv.conf template
  template:
    src: templates/resolv.conf
    dest: /etc/resolv.conf

- name: Apply the hosts template
  template:
    src: templates/hosts
    dest: /etc/hosts

- name: Set the default interface for cucumber Linux
  set_fact:
    ansible_default_ipv4:
      interface: "eno666"

- name: Apply the interfaces template
  template:
    src: templates/cuc-interfaces
    dest: /etc/network/interfaces

- name: Restart network WARN This will break connection
  service:
      name: networking
      state: restarted
  async: 2
  poll: 0

