---
- name: Apply the resolv.conf template
  template:
    src: templates/resolv.conf
    dest: /etc/resolv.conf

- name: Apply the hosts template
  template:
    src: templates/hosts
    dest: /etc/hosts

- name: Apply the interfaces template
  template:
    src: templates/opensuseinterface
    dest: /etc/sysconfig/network/ifcfg-eth0

- name: Apply the routes template
  template:
    src: templates/opensuse-routes
    dest: /etc/sysconfig/network/routes

- name: Restart network WARN This will break connection
  service:
      name: networking
      state: restarted
  async: 2
  poll: 0

