---
- name: Copy configure script
  win_template:
    src: configure.j2
    dest: C:\Setup-hMail.ps1

- name: Copy hMail server executable
  win_copy:
    src: ./files/hmailserver.exe
    dest: C:\hmailserver.exe

- name: Install hMail server
  win_package:
    path: C:\hmailserver.exe
    state: present
    product_id: hMailServer_is1
    arguments: /verysilent
  register: mail_result

- name: Reboot once hMail server installed
  when: mail_result.reboot_required == true
  win_reboot:

- name: Run hMail installation script
  win_command: powershell.exe C:\Setup-hMail.ps1 
