---
- name: Install IIS modules
  win_feature:
    name:
      - Web-Server
      #- Web-Default-Doc
      #- Web-Dir-Browsing
      #- Web-Http-Errors
      #- Web-Static-Content
      #- Web-Mgmt-Console
    state: present
  register: iis_result

- name: Reboot once IIS installed
  win_reboot:
  when: iis_result.reboot_required

- name: Copy SSL binding script
  win_copy:
    src: files/ssl_binding.ps1
    dest: C:\ssl_binding.ps1

- name: Generate SSL binding for IIS
  win_command: powershell.exe -executionpolicy bypass C:\ssl_binding.ps1

- name: Restart web sevice
  win_service:
    name: W3SVC
    state: restarted
    start_mode: auto
