---
- name: Add local user accounts
  win_user:
    name: "{{ item }}"
    password: "{{ default_password }}" 
    state: present
    groups:
      - Users
    group_action: add
    account_locked: no
    account_disabled: no
    password_expired: no
    update_password: on_create
    user_cannot_change_password: no
  loop:
    - jeff
    - martha

- name: Add local admin accounts
  win_user:
    name: "{{ item }}"
    password: "{{ default_password }}"
    state: present
    groups:
      - Administrators
    group_action: add
    account_locked: no
    account_disabled: no
    password_expired: no
    update_password: on_create
    user_cannot_change_password: no
  loop:
    - hello
    - darkness
    - my
    - old
    - friend