---
- name: An Nginx has appeared
  yum_repository:
    name: nginx
    description: Nginx?
    baseurl: http://nginx.org/packages/centos/7/x86_64/
    enabled: yes
    gpgcheck: no
    state: present

- name: Install/Setup Nginx
  package:
    name: '{{ item }}'
    state: installed
  with_items:
    - nginx

- name: Copy Nginx config
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0600'
  notify: Restart nginx

- name: nginx ssl directory create
  file:
    path: /etc/nginx/ssl
    owner: root
    group: root
    state: directory

- name: nginx ssl directory permission
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: 0755

- name: Stat DH key
  stat:
    path: /etc/nginx/ssl/dhparam.pem
  register: stat_dhparam
- shell: openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
  when: stat_dhparam.stat.exists == False
  
- name: Create OpenSSL custom cert for Graylog
  shell: openssl req -new -nodes -x509 -days 365 -subj "/C={{ cert_country }}/ST={{ cert_state }}/L={{ cert_local }}/O={{ cert_org }}/CN={{ ossec_hostname }}" -keyout /etc/nginx/ssl/graylog.key -out /etc/nginx/ssl/graylog.crt
  when: stat_dhparam.stat.exists == False

- name: Copy Nginx graylog site
  template:
    src: templates/nginx_graylog.conf
    dest: /etc/nginx/conf.d/nginx_graylog.conf
    owner: root
    group: root
    mode: '0600'
  notify: Restart nginx

- name: enable Nginx
  service:
    name: nginx
    enabled: yes
